# Generated by Django 3.0.6 on 2020-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to='File/%y/%m/%d/'),
        ),
    ]
