# Generated by Django 3.0.6 on 2020-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200520_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=550, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(to='User.Publications'),
        ),
    ]
